#!/bin/bash

echo "📧 ПОШАГОВАЯ ИНСТРУКЦИЯ: Регистрация в Brevo (ex-Sendinblue)"
echo "=============================================================="
echo ""
echo "🎯 Brevo - отличная бесплатная альтернатива SendGrid"
echo "✅ 300 писем/день бесплатно"
echo "✅ Не требует кредитной карты"
echo "✅ Простая настройка"
echo ""
echo "🔧 ПОШАГОВАЯ НАСТРОЙКА:"
echo ""
echo "1️⃣  Регистрация в Brevo:"
echo "   - Откройте: https://www.brevo.com"
echo "   - Нажмите 'Sign up free'"
echo "   - Введите данные:"
echo "     * Email: vpfilter111@gmail.com"
echo "     * Password: любой надежный пароль"
echo "     * Company: Sport Predictions"
echo "   - Подтвердите email адрес"
echo ""
echo "2️⃣  Получение SMTP ключа:"
echo "   - Войдите в панель Brevo"
echo "   - Перейдите: Settings → SMTP & API"
echo "   - Нажмите 'Generate a new SMTP key'"
echo "   - Скопируйте SMTP key (выглядит как длинная строка)"
echo ""
echo "3️⃣  Обновление .env.production:"
echo "   BREVO_USER=vpfilter111@gmail.com"
echo "   BREVO_SMTP_KEY=ваш-длинный-smtp-ключ"
echo ""
echo "4️⃣  Перезапуск Docker:"
echo "   docker compose down"
echo "   docker compose build --no-cache backend"
echo "   docker compose up -d"
echo ""
echo "🔗 Полезные ссылки:"
echo "   Регистрация: https://www.brevo.com/products/transactional-email/"
echo "   Документация: https://developers.brevo.com/docs"
echo ""
echo "📝 ВАЖНЫЕ ЗАМЕТКИ:"
echo "   - Регистрация займет 3-5 минут"
echo "   - SMTP ключ выглядит примерно так: xsmtpsib-a1b2c3d4..."
echo "   - После подтверждения email сразу можно отправлять письма"
echo "   - Лимит: 300 писем/день (более чем достаточно)"
echo ""
echo "🧪 ТЕСТИРОВАНИЕ:"
echo "   После настройки запустите:"
echo "   cd /app/backend"
echo "   node -e \"require('./services/emailServiceUniversal').testEmailService()\""
echo ""
echo "✅ После выполнения этих шагов email будет работать идеально!"
echo ""