#!/bin/bash

echo "🔐 Инструкция для получения Gmail App Password"
echo "=============================================="
echo ""
echo "📧 Для работы Gmail SMTP нужен App Password (пароль приложения)"
echo ""
echo "🔧 Пошаговая инструкция:"
echo ""
echo "1. Откройте Google Account: https://myaccount.google.com"
echo "2. Перейдите в 'Security' (Безопасность)"
echo "3. Включите 2-Step Verification (если еще не включено)"
echo "4. Найдите 'App passwords' (Пароли приложений)"
echo "5. Выберите 'Mail' и 'Other (custom name)'"
echo "6. Введите название: 'Sport Predictions Website'"
echo "7. Скопируйте 16-значный пароль (например: abcd efgh ijkl mnop)"
echo ""
echo "📝 Затем обновите .env.production:"
echo "GMAIL_USER=vpfilter111@gmail.com"
echo "GMAIL_APP_PASSWORD=abcdefghijklmnop"
echo ""
echo "🚨 ВАЖНО:"
echo "- Используйте App Password, НЕ обычный пароль от Gmail!"
echo "- App Password выглядит как: abcdefghijklmnop (16 символов)"
echo "- Обычный пароль от Gmail НЕ работает с SMTP!"
echo ""
echo "✅ После настройки Gmail SMTP будет работать на 100%"
echo ""
echo "🔗 Прямая ссылка для создания App Password:"
echo "https://myaccount.google.com/apppasswords"
echo ""